### ISSUE TITLE
Bug: Chapter 6 "fashionMNIST_foolbox_boundary.ipynb" 

### ISSUE THREAD

**Issue by JafarBadour** [katywarr/strengthening-dnns#3]
# Main issue
I think the code was written with an older version of foolbox or tensorflow. Because while running 
cell 
```
x_adv = attack(input_or_adv=x, 
               label = y,
               starting_point = starting_point_image,
               unpack = False,
               iterations = 2000,
               log_every_n_steps = 500)
```
This error arises:
```
TypeError  Traceback (most recent call last)
<ipython-input-20-f0698dcd1aa3> in <module>()
      4                unpack = False,
      5                iterations = 2000,
----> 6                log_every_n_steps = 500)

TypeError: __call__() missing 2 required positional arguments: 'inputs' and 'labels'
```

I tried renaming ```input_or_adv ``` to ```inputs```and ```label``` to ```np.ndarray([y])``` but it doesnt work. the ```labels``` lengths and ```inputs``` length should be equal.

here is a link of what i had done on google colab

[Colab link](https://colab.research.google.com/drive/1-3F55BpBQrFKmRuSGZHmGfFu2fIs9L02)

**Comment by katywarr** [comment]
Hi @JafarBadour

I haven't been able to recreate this problem. Please could you let me know your versions of tensorflow and  FoolBox? They should be as per the [requirements.txt](https://github.com/katywarr/strengthening-dnns/blob/master/requirements.txt) file. 

Many thanks,
Katy

**Comment by JafarBadour** [comment]
I have solved it by making virtual environment and installing older version of tensorflow ... problem was because of new version. Thank you for reply.
