### ISSUE TITLE
#err: Chapter10: NoteBook Cell is not updated

### ISSUE THREAD

**Issue by JafarBadour** [katywarr/strengthening-dnns#4]
# Notebook cell in [chap10notebook](https://github.com/katywarr/strengthening-dnns/blob/master/chapter10/fashionMNIST_adversarial_training.ipynb)

Cell number 6 is not properly run, I ran it and it is working properly, its just in need of update in repo

# Output in repo
![image](https://user-images.githubusercontent.com/16943355/79733492-e3e51780-82fd-11ea-8a9a-b4008c46a29f.png)

# Output should be
![image](https://user-images.githubusercontent.com/16943355/79733601-0d05a800-82fe-11ea-805b-398b06ee2ee3.png)

**Comment by katywarr** [comment]
Fixed with [this commit](https://github.com/katywarr/strengthening-dnns/commit/fd23162536ef92d916290536ef6ed330ffd08bc2). Please re-open if you still see problems.
