### ISSUE TITLE
Bug: generate_adversarial_data does not work with colored images

### ISSUE THREAD

**Issue by JafarBadour** [katywarr/strengthening-dnns#5]
# generate_adversarial_data doesnt work with colored images

It says value error that element at index 0 has 3 dimensions while element at index 1 has 4

**Comment by JafarBadour** [comment]
I fixed the issue by changing the code in [adversarial_utils.py](https://github.com/katywarr/strengthening-dnns/blob/master/strengtheningdnns/adversarial_utils.py) in line 30 from 

```python
adv_images = np.empty((0, original_images.shape[1], original_images.shape[2]),
                          dtype=int)
```
to
```python
adv_images = np.empty((0, original_images.shape[1], original_images.shape[2], \
original_images.shape[3]), dtype=int)
```

**Comment by katywarr** [comment]
Thank you @JafarBadour for opening this issue and suggesting the fix.
Please re-open if there is still a problem.
